title: USDM County Aggregations
description: Weekly US Drought Monitor (USDM) data aggregated to US Census county boundaries
author: R. Kyle Bocinsky
url: "https://climate-smart-usda.github.io/usdm-counties/"  # Your GitHub Pages URL
baseurl: "/usdm-counties"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# minima:
#   skin: classic